# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce107efa7c0bd37645b5809737a95c120734df1aabd85f5fabf4bdc388751d1eace9365d40df84329b233ea5e94bf7387f706354423e6006cc98de8e87495c7c

test:
  secret_key_base: 6596b1b80723407bc085411385d18a18835f7e23fc334803ad87c5f1addb54aaa3b1f4a81c0186020752e8b1c3e9bbb0d20ebb597dd53c8df971b0327ea9848a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
